version: "3.1"

services:
  source2bids:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fnirs-apps/source2bids
    volumes:
      - /Volumes/MassStorage2TB/rluke/Repositories/BIDS-NIRS-Tapping/:/bids_dataset
    command: ["--task_label", "tapping"]
