name: "Tests"
on:
- pull_request

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Download test NIRX data
        shell: bash -el {0}
        run: |
          curl -L https://github.com/rob-luke/BIDS-NIRS-Tapping/archive/00-Raw-data.zip --output data.zip
          pwd
          unzip data.zip -d ~/example_data
          ls

      - name: Download test NIRX SNIRF data
        shell: bash -el {0}
        run: |
          curl -L https://github.com/rob-luke/example-bids-sourcedata-snirf-nirx/archive/main.zip --output data_snirf.zip
          pwd
          unzip data_snirf.zip -d ~/example_data_nirx_snirf
          ls

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker-compose build

      - name: Run docker image
        run: docker-compose up

      - name: Build docker image
        run: docker build --progress=plain -t test .
          
      - name: Run test with minimal arguments
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-00-Raw-data/:/bids_dataset test --task-label tapping
        
      - name: Run test with single subject
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-00-Raw-data/:/bids_dataset test --task-label tapping --subject-label 03
        
      - name: Run test with manual duration
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-00-Raw-data/:/bids_dataset test --task-label tapping --duration 3
        
      - name: Run test with multiple arguments
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-00-Raw-data/:/bids_dataset test --task-label tapping --duration 3  --subject-label 02

      - name: Run test with custom events
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-00-Raw-data/:/bids_dataset test --task-label tapping --events "{\"1\":\"Control\", \"2\":\"Tapping/Left\", \"3\":\"Tapping/Right\"}" --duration 5

      - name: Ensure generated dataset was valid
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-00-Raw-data/:/bids_dataset -v /home/runner/work/fnirs-apps-sourcedata2bids/fnirs-apps-sourcedata2bids/.github/workflows/tests_script.py:/script.py ghcr.io/rob-luke/mne-nirs/image python /script.py

      - uses: actions/upload-artifact@v1
        name: Upload formatted BIDS dataset
        with:
          name: Formatted_BIDS_Dataset
          path: /home/runner/example_data/BIDS-NIRS-Tapping-00-Raw-data

      - name: NIRX SNIRF data test
        run: docker run -v /home/runner/example_data_nirx_snirf/example-bids-sourcedata-snirf-nirx-main/:/bids_dataset test --task-label snirftap

      - name: NIRX SNIRF data test with optode frame
        run: docker run -v /home/runner/example_data_nirx_snirf/example-bids-sourcedata-snirf-nirx-main/:/bids_dataset test --task-label snirftap --optode-frame mri